Feature/stacktraces for debug logging
corona-warn-app/cwa-server pull request #1065
Opened 2020-12-10 14:38 UTC by kilbphilippSAP

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn -P integration-tests clean verify` runs for the whole project and, if you touched any code in the respective [service](services), ensure it can be run with `spring-boot:run`

## Description

* Branched from [PR#1044](https://github.com/corona-warn-app/cwa-server/pull/1044)
* Reintroduce Stacktraces in Errors

2020-12-14 10:27 UTC, roesslerj requested changes

2020-12-14 10:27 UTC, roesslerj commented on services/download/src/main/java/app/coronawarn/server/services/download/BatchDownloadException.java
>  public class BatchDownloadException extends RuntimeException {
Now seeing this: Maybe we should change the type to a checked exception? Because we want to make sure that we catch every instance.

2020-12-14 10:27 UTC, roesslerj commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> -    } catch (BatchDownloadException e) {
Point in case: checked exception...

2020-12-14 10:27 UTC, roesslerj commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> +          "Triggering download of first batch for date {} failed.",
I personally like this in one line. What's your configured max line length? I think we have 120 chars in checkstyle.

2020-12-14 10:27 UTC, roesslerj commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> +          e);
Same as above: Keep in one line?

2020-12-14 10:27 UTC, roesslerj commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> -    } catch (BatchDownloadException e) {
Now I am in strong favour of having BatchDownloadException being a checked exception :-)

2020-12-14 10:58 UTC, roesslerj approved these changes, later dismissed

2020-12-15 06:53 UTC, mibrasap requested changes

2020-12-15 06:53 UTC, mibrasap commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> -      logger.info("Building diagnosis key from federation diagnosis key failed. Reason: {}.", e.getMessage());
What about logging also date and batchTag in this case?

2020-12-15 10:00 UTC, mibrasap approved these changes, later dismissed

2020-12-15 12:29 UTC, roesslerj submitted a review, later dismissed

2020-12-15 15:13 UTC, mibrasap approved these changes, later dismissed

2020-12-15 15:28 UTC, hilmarf approved these changes, later dismissed

2020-12-17 09:43 UTC, hilmarf approved these changes

2020-12-17 12:04 UTC, mibrasap approved these changes

2020-12-17 12:05 UTC, merged