Update the name of EFGS_CERT_CN in codebase as it is in vault.
corona-warn-app/cwa-server pull request #1141
Opened 2021-01-15 15:05 UTC by ioangut

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn -P integration-tests clean verify` runs for the whole project and, if you touched any code for a service in the `services` folder, ensure it can be run with `spring-boot:run`

2021-01-15 15:06 UTC, hilmarf approved these changes, later dismissed

2021-01-17 18:06 UTC, mibrasap requested changes

2021-01-17 18:06 UTC, mibrasap commented on services/callback/src/main/resources/application.yaml
> +    efgs-cert-cn: ${EFGS_CERT_CN:}
```suggestion
    efgs-cert-cn: ${EFGS_CERT_CN}
```

2021-01-18 08:18 UTC, mibrasap approved these changes

2021-01-18 08:21 UTC, kilbphilippSAP approved these changes

2021-01-18 08:21 UTC, merged