Enhancement/statistics logging
corona-warn-app/cwa-server pull request #1156
Opened 2021-01-20 11:13 UTC by fredrb

- Add logs to successful creation of cards
- Add debug logs with used JSON entries

The idea was to add which parts of the statistic JSON object were used to create the cards. Therefore the logs will collected and print all entries looked when `debug` profile is active. For example:

```
2021-01-20T11:56:19+0100 WARN  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-20] Some required properties are missing in JSON file for card Infections Card 
2021-01-20T11:56:19+0100 WARN  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-20] Some required properties are missing in JSON file for card Key Submission Card 
2021-01-20T11:56:19+0100 WARN  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-20] Some required properties are missing in JSON file for card Incidence Card 
2021-01-20T11:56:19+0100 INFO  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-20] Reproduction Number Card successfully created 
2021-01-20T11:56:19+0100 INFO  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-19] Infections Card successfully created 
2021-01-20T11:56:19+0100 INFO  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-19] Key Submission Card successfully created 
2021-01-20T11:56:19+0100 INFO  main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-19] Incidence Card successfully created 
2021-01-20T11:56:19+0100 DEBUG main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: The following statistics JSON entries were used to create the cards. Null values are omitted. 
2021-01-20T11:56:19+0100 DEBUG main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-20] {"sevenDayRvaluePublishedDaily":0.87,"effective_date":"2021-01-20","seven_day_incidence_1st_reported_trend_1percent":1,"seven_day_r_value_published_daily":0.87,"seven_day_r_value_published_growthrate":0.9775280898876404,"seven_day_r_value_published_trend_1percent":-1,"update_timestamp":"2021-01-20T09:12:37,375"} 
2021-01-20T11:56:19+0100 DEBUG main a.c.s.s.d.s.StatisticsToProtobufMapping[72480]: [2021-01-19] {"sevenDayRvaluePublishedDaily":0.89,"app_downloads_7days_avg":"21471.428571428572","app_downloads_7days_avg_growthrate":0,"app_downloads_7days_sum":150300,"app_downloads_7days_avg_trend_5percent":-1,"app_downloads_cumulated":25185243,"app_downloads_daily":24336,"effective_date":"2021-01-19","infections_effective_7days_avg":16368,"infections_effective_7days_avg_growthrate":0.7913854909897153,"infections_effective_7days_avg_trend_5percent":-1,"infections_effective_cumulated":2068002,"infections_effective_daily":15974,"labs_connected_cumulated":175,"labs_registered_cumulated":182,"persons_who_shared_keys_7days_avg_growthrate":0.7632318940198712,"persons_who_shared_keys_7days_sum":12214,"persons_who_shared_keys_7days_avg_trend_5percent":-1,"persons_who_shared_keys_cumulated":215584,"persons_who_shared_keys_daily":2415,"persons_who_shared_keys_7days_avg":1744,"seven_day_incidence_1st_reported_daily":123.49171773788191,"seven_day_incidence_1st_reported_growthrate":0.939093860010058,"seven_day_incidence_1st_reported_trend_1percent":-1,"seven_day_r_value_published_daily":0.89,"seven_day_r_value_published_growthrate":0.9569892473118279,"seven_day_r_value_published_trend_1percent":-1,"update_timestamp":"2021-01-20T09:12:37,375"} 
```

The JSON is encoded into String to be printed on the terminal. For a formatted view you can paste the line in a text editor or some online JSON parsing tool like [this one](http://json.parser.online.fr/).

2021-01-20 12:06 UTC, hilmarf requested changes

2021-01-20 12:06 UTC, hilmarf commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/StatisticsToProtobufMapping.java
> +
can we put this into `if` condition, where the actual set log-level is checked?

2021-01-20 12:55 UTC, hilmarf approved these changes

2021-01-21 15:25 UTC, FelixRottler approved these changes

2021-01-21 15:30 UTC, merged