Bugfix/statistics ignored values
corona-warn-app/cwa-server pull request #1169
Opened 2021-02-01 14:06 UTC by ioangut

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn -P integration-tests clean verify` runs for the whole project and, if you touched any code for a service in the `services` folder, ensure it can be run with `spring-boot:run`

## Description

Apply to all relevant JSON properties the Processing Values logic(ignore properties that has values <= 0) except for the trend ones.

2021-02-01 15:06 UTC, hilmarf commented on runconfigs/IntelliJ/callback [spring-boot_run...].run.xml
> +  <configuration default="false" name="callback [spring-boot:run...]" type="MavenRunConfiguration" factoryName="Maven" nameIsGenerated="true">
@ioangut please exclude this file from the PR as it's not related to the fix

2021-02-01 15:24 UTC, mibrasap submitted a review, later dismissed

2021-02-02 13:40 UTC, hilmarf commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/keyfigurecard/factory/IncidenceCardFactory.java
> +      return List.of(Optional.empty());
```suggestion
      return Collections.emptyList();
```

2021-02-02 13:41 UTC, hilmarf commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/keyfigurecard/factory/InfectionsCardFactory.java
> +      return List.of(Optional.empty());
```suggestion
      return Collections.emptyList();
```

2021-02-02 13:42 UTC, hilmarf commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/keyfigurecard/factory/KeySubmissionCardFactory.java
> +      return List.of(Optional.empty());
```suggestion
      return Collections.emptyList();
```

2021-02-02 13:42 UTC, hilmarf commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/keyfigurecard/factory/ReproductionNumberCardFactory.java
> +      return List.of(Optional.empty());
```suggestion
      return Collections.emptyList();
```

2021-02-02 13:44 UTC, hilmarf requested changes
👍

2021-02-02 15:27 UTC, hilmarf submitted a review, later dismissed

2021-02-03 10:00 UTC, hilmarf approved these changes

2021-02-04 08:19 UTC, FelixRottler commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/keyfigurecard/factory/HeaderCardFactory.java
> +    var nullFieldsOrZeroOrLessThanZero = getRequiredFieldValues(stats).stream()
Guess this could be simplified to xx.stream().anyMatch(Optional::isEmpty)

2021-02-04 08:19 UTC, FelixRottler approved these changes

2021-02-04 09:06 UTC, merged