Merge release2 into main
corona-warn-app/cwa-server pull request #1319
Opened 2021-04-07 12:28 UTC by ioangut

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn -P integration-tests clean verify` runs for the whole project and, if you touched any code for a service in the `services` folder, ensure it can be run with `spring-boot:run`

## Description

This PR merges the release/2.0 branch into the main branch with the additional features introduced.

2021-04-07 12:32 UTC, roesslerj requested changes

2021-04-07 12:32 UTC, roesslerj commented on .mvn/maven.config
> +-Drevision=2.0.0
It's now 2.1.0-SNAPSHOT, right?

2021-04-07 12:40 UTC, ioangut commented on .mvn/maven.config
> +-Drevision=2.0.0
```suggestion
-Drevision=2.1.0-SNAPSHOT
```

2021-04-09 08:52 UTC, roesslerj approved these changes

2021-04-09 13:52 UTC, pithumke approved these changes

2021-04-09 13:52 UTC, merged