Submission handler test
corona-warn-app/cwa-server pull request #1358
Opened 2021-04-26 11:42 UTC by ioangut

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn -P integration-tests clean verify` runs for the whole project and, if you touched any code for a service in the `services` folder, ensure it can be run with `spring-boot:run`

## Description

Add timeout handler for SubmissionController and FakeRequestController requests.

2021-04-26 11:47 UTC, hilmarf commented on services/submission/src/main/java/app/coronawarn/server/services/submission/controller/SubmissionController.java
> +            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)));
how do the logs look like in case of a timeout?

2021-04-28 08:15 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/audit/ExecutionTimeAspect.java
> +  private Logger logger = LoggerFactory.getLogger(ExecutionTimeAspect.class);
I think logger is not used in this class, right?

2021-04-28 08:15 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/audit/ExecutionTimeAspect.java
> +  private TrackExecutionTimeProcessor trackExecutionTimeProcessor;
We should check if we can use constructor injection

2021-04-28 08:16 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/audit/ExecutionTimeAspect.java
> +   * Return an object.
Improve comment: Returns the actual return value of the called method

2021-04-28 08:16 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/audit/ExecutionTimeAspect.java
> +    Long trackSystemMillis = System.currentTimeMillis();
Maybe we can call this "startTime"? Would do you think?

2021-04-28 08:21 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/audit/TrackExecutionTimeProcessor.java
> +   * @param name        of the class
Improve doc: String methodName name of the executed method.

2021-04-28 08:30 UTC, FelixRottler requested changes
I think we need more tests in order to make sure that the requestscoped bean is not polluted by different requests..... Additionally I think we should talk about where to apply the annotation. Maybe we can apply the annotation to methods that are business logic (database/feign etc.) instead of counters/getters

2022-05-09 11:40 UTC, closed without merging