Feature/vaccination statistics
corona-warn-app/cwa-server pull request #1408
Opened 2021-05-28 08:14 UTC by AliceBilc

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `mvn -P integration-test clean verify` runs for the whole project and, if you touched any code for a service in the `services` folder, ensure it can be run with `spring-boot:run`

## Description

Added three new cards for vaccination statistics.

2021-05-28 12:03 UTC, hilmarf approved these changes

2021-06-01 06:34 UTC, FelixRottler commented on services/distribution/src/test/java/app/coronawarn/server/services/distribution/statistics/KeyFigureCardFactoryTest.java
> +  @ExtendWith(SpringExtension.class)
Is it possible to remove this annotations except ``@Nested``?  I think if the outer class provides this annotations then it should be enough. What do you think?

2021-06-01 06:37 UTC, FelixRottler commented on services/distribution/src/test/java/app/coronawarn/server/services/distribution/statistics/KeyFigureCardFactoryTest.java
> +  @ExtendWith(SpringExtension.class)
Same here (if it is possible)

2021-06-01 06:37 UTC, FelixRottler commented on services/distribution/src/test/java/app/coronawarn/server/services/distribution/statistics/KeyFigureCardFactoryTest.java
> +    void shouldThrowAnExceptionIfMandatoryPropertyIsEqualToZero() {
These could maybe collapsed into one ParameterizedTest ( testing if an Exception is thrown)

2021-06-01 06:39 UTC, FelixRottler commented on services/distribution/src/test/java/app/coronawarn/server/services/distribution/statistics/KeyFigureCardFactoryTest.java
> +    void shouldThrowAnExceptionIfMandatoryPropertyIsEqualToZero() {
This can maybe also collapsed into one single ParameterizedTest

2021-06-01 06:39 UTC, FelixRottler commented on services/distribution/src/test/java/app/coronawarn/server/services/distribution/statistics/KeyFigureCardFactoryTest.java
> +  @ExtendWith(SpringExtension.class)
Same here (if it is possible)

2021-06-01 06:39 UTC, FelixRottler commented on services/distribution/src/test/java/app/coronawarn/server/services/distribution/statistics/KeyFigureCardFactoryTest.java
> +    void shouldThrowAnExceptionIfMandatoryPropertyIsEqualToZero() {
Same here ( collapsing)

2021-06-01 06:41 UTC, FelixRottler requested changes
see comments :)

2021-06-01 16:21 UTC, FelixRottler approved these changes

2021-06-01 16:21 UTC, merged