Feature/certificate rules
corona-warn-app/cwa-server pull request #1471
Opened 2021-07-02 11:26 UTC by alexmoroianu

2021-07-06 12:14 UTC, ioangut commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/dgc/DigitalGreenCertificateToCborMapping.java
> +   *git s
Is this a typo?

2021-07-06 12:20 UTC, alexmoroianu commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/dgc/DigitalGreenCertificateToCborMapping.java
> +   *git s
yep :D fixed

2021-07-06 12:36 UTC, ioangut approved these changes

2021-07-06 12:54 UTC, AliceBilc approved these changes

2021-07-07 10:40 UTC, roesslerj requested changes
I think in general it doesn't make sense to mix two different edge-case handling strategies. Either we should use Optional throughout, or throw exceptions if we can't connect to the servers or can't find the files. Mixing both makes the code complex and error-prone IMHO. What do you think?

2021-07-07 10:40 UTC, roesslerj commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/dgc/DigitalGreenCertificateToProtobufMapping.java
> +    return result.get();
Why not throwing a custom exception here (UnableToLoadFileException or DigitalCovidCertificateException)? We don't want the NoSuchElementException here!

2021-07-07 10:40 UTC, roesslerj commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/dgc/DigitalGreenCertificateToProtobufMapping.java
> +      return Optional.empty();
Why not simply declare the thrown exception? Would make all else easier, or not?

2021-07-07 14:01 UTC, roesslerj approved these changes

2021-07-07 16:08 UTC, merged