Feature/submission on behalf
corona-warn-app/cwa-server pull request #1538
Opened 2021-08-18 16:12 UTC by FelixRottler

- draft PR for keeping track of the progress for submission on behalf

2021-08-19 11:59 UTC, AliceBilc approved these changes

2021-08-19 11:59 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/checkins/EventCheckInProtectedReportsValidator.java
> +      addViolation(context, "Checkins protected reports must contain items that all share the same location id hash.s");
```suggestion
      addViolation(context, "Checkins protected reports must contain items that all share the same location id hash.");
```

2021-08-19 11:59 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/checkins/EventCheckInProtectedReportsValidator.java
> +      logger.warn(SECURITY, "Checkins must contain items that all share the same location id");
```suggestion
      logger.warn(SECURITY, "Checkins protected reports must contain items that all share the same location id");
```

2021-08-19 12:00 UTC, FelixRottler commented on services/submission/src/main/java/app/coronawarn/server/services/submission/checkins/EventCheckInProtectedReportsValidator.java
> +   * @param submissionPayload the submission paylaod to validate.
```suggestion
   * @param submissionPayload the submission payload to validate.
```

2021-08-20 08:34 UTC, roesslerj requested changes

2021-08-20 08:34 UTC, roesslerj commented on services/submission/src/test/resources/application.yaml
> +        connect-timeout: 900
Was this changed on purpose? Why?

2021-08-20 08:34 UTC, roesslerj approved these changes

2021-08-20 08:35 UTC, merged