License change: switch from CLA to DCO
corona-warn-app/cwa-server pull request #795
Opened 2020-09-21 13:00 UTC by ebratter

## Checklist

* [X] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [X] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description
To adopt external standards and best practices wherever possible and to make contributions to our open source projects as easy as possible, we (the SAP Open Source Program Office) introduce some changes to our publishing guidelines.

SAP open source projects are supposed to move from CLA to DCO and use REUSE to declare licenses and copyright.

- Contributors now need to accept the standard Linux Developer Certificate of Origin instead of the formerly used SAP Contributor License Agreement.
- License and copyright information is now specified in REUSE format.

2020-09-30 14:19 UTC, hilmarf approved these changes

2020-09-30 14:20 UTC, fredrb requested changes
Full project search doesn't show any licenses header. Looks good

2020-09-30 14:20 UTC, fredrb commented on .github/workflows/license-analysis.yml
> +
remove unnecessary tab

2020-09-30 14:21 UTC, fredrb requested changes

2020-09-30 14:21 UTC, fredrb commented on .github/workflows/license-analysis.yml
> +
```suggestion

```

2020-10-01 16:40 UTC, fredrb approved these changes

2020-10-01 17:51 UTC, hilmarf approved these changes

2020-10-01 17:53 UTC, merged