Feature/merge master into federation
corona-warn-app/cwa-server pull request #829
Opened 2020-09-30 11:35 UTC by ioangut

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

Merge master into federation branch.

2020-09-30 11:56 UTC, hilmarf requested changes

2020-09-30 11:56 UTC, hilmarf commented on services/submission/pom.xml
> +    </dependency>
not required - please remove

2020-09-30 11:56 UTC, hilmarf commented on services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
> +import static app.coronawarn.server.services.submission.controller.SubmissionPayloadMockData.*;
is this a checkstyle rule?
normally ...* imports should be avoided

2020-09-30 14:11 UTC, hilmarf commented on services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/ProdDiagnosisKeyBundler.java
> +import static java.time.ZoneOffset.UTC;
unsused import

2020-10-01 07:53 UTC, EugenM-SAP commented on services/submission/src/test/java/app/coronawarn/server/services/submission/controller/RequestExecutor.java
> +  public static TemporaryExposureKey buildTemporaryExposureKey(
I believe these helper methods are not needed in RequestExecutor. They have been moved to SubmissionPayloadMockData in the federation branch. I think they should not be  "brought" in from master

2020-10-01 12:19 UTC, EugenM-SAP approved these changes

2020-10-01 12:57 UTC, sorin-stefan-iovita-sap approved these changes

2020-10-01 16:39 UTC, fredrb approved these changes

2020-10-01 18:15 UTC, merged