Fix test using different time zone clocks
corona-warn-app/cwa-server pull request #841
Opened 2020-10-02 08:44 UTC by EugenM-SAP

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

2020-10-02 09:28 UTC, hilmarf requested changes

2020-10-02 09:28 UTC, hilmarf commented on common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyServiceTestHelper.java
> +    LocalDateTime yesterday = LocalDateTime.of(LocalDate.now(ZoneId.of("UTC")), LocalTime.MIDNIGHT).minusDays(1);
consider usage of public statics `ZoneOffset.UTC` instead of fetching UTC with string

2020-10-02 09:28 UTC, hilmarf commented on common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/common/DiagnosisKeyExpirationCheckerTest.java
> +    LocalDateTime midnight = LocalDateTime.of(LocalDate.now(ZoneId.of("UTC")), LocalTime.MIDNIGHT);
consider usage of public statics `ZoneOffset.UTC` instead of fetching UTC with string

2020-10-02 09:28 UTC, hilmarf commented on common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/common/DiagnosisKeyExpirationCheckerTest.java
> +    LocalDateTime midnight = LocalDateTime.of(LocalDate.now(ZoneId.of("UTC")), LocalTime.MIDNIGHT);
consider usage of public statics `ZoneOffset.UTC` instead of fetching UTC with string

2020-10-02 14:06 UTC, JonasZeitzem-sap commented on common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/common/DiagnosisKeyExpirationCheckerTest.java
> +    LocalDateTime midnight = LocalDateTime.of(LocalDate.now(ZoneId.of("UTC")), LocalTime.MIDNIGHT);
You missed to remove the String parameter once.

2020-10-02 14:48 UTC, hilmarf requested changes

2020-10-02 14:48 UTC, hilmarf commented on common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/common/DiagnosisKeyExpirationCheckerTest.java
> +import java.time.ZoneId;
unused import

2020-10-05 07:57 UTC, JonasZeitzem-sap approved these changes

2020-10-05 08:01 UTC, mibrasap approved these changes

2020-10-05 08:03 UTC, hilmarf approved these changes

2020-10-05 08:04 UTC, merged