Feature/federation download filtering
corona-warn-app/cwa-server pull request #843
Opened 2020-10-02 12:47 UTC by mibrasap

2020-10-05 08:27 UTC, EugenM-SAP commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> +        int invalidKeys = diagnosisKeyBatch.getKeysCount() - validDiagnosisKeys.size();
Worth extracting a method here : logInvalidKeys()

2020-10-05 08:31 UTC, EugenM-SAP commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> +          try {
worth to extract a method for trying to create the DiagnosisKey from the federation key and hide the try catch.

Maybe map(
                 Optional.of(  transformToDiagnosisKey(federationKey) ) 
            ....)

2020-10-06 06:56 UTC, kilbphilippSAP approved these changes

2020-10-06 07:21 UTC, EugenM-SAP approved these changes

2020-10-06 07:21 UTC, merged

2020-10-06 07:51 UTC, fredrb requested changes
I don't understand why some of this validations are being done in Download. The validation if a DiagnosisKey is valid or not should already be covered on the DiagnosisKey builder, and the definition of what is a valid field mapped in the properties of our Persistence Class. Take `rollingPeriod` for example, [DiagnosisKey](https://github.com/corona-warn-app/cwa-server/blob/master/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L49-L51) domain class already annotates what are the valid values. 

Therefore, I feel like the "validation loop" does very similar validations twice in a row. It first filters all the keys that are valid, then calls the builder to create DiagnosisKeys. The build will work for every key because the invalid ones were already filtered out.  

```java
    return diagnosisKeyBatch.getKeysList()
        .stream()
        .filter(validFederationKeyFilter::isValid) // <-- Validates all fields
        .map(this::convertFederationDiagnosisKeyToDiagnosisKey)  // <-- Validates all fields again
```

This works, but I feel like it's misleading. Because sometime we rely on a separate validator class (i.e. ValidFederationKeyFilter) and sometime on the validations defined in our Model class (i.e. domain/DiagnosisKey). Maybe some validations are needed specifically on Download, but I don't think all of them are. 

The second thing about this is that we are now keeping validation ranges in multiple places:

1. [DiagnosisKey](https://github.com/corona-warn-app/cwa-server/blob/master/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L37-L38) class has a static public constant for Rolling period and hardcodes other values. This PR adds the same values in `application.yaml`
2. #842 adds ranges for checking DSOS hardcoded. This PR added the same values in `application.yaml`. I raised the same point in the PR. We are having awfully similar values defined in many places. 

Maybe it's fine to have these values as constants as they won't change often (or ever), and avoid cluttering `application.yaml` with a lot of constants. But whatever we choose, we should always read from the same place.

2020-10-06 07:51 UTC, fredrb commented on services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
> +      logger.info("Building key failed.");
```suggestion
      logger.error("Building key failed.", ex);
```

2020-10-06 07:51 UTC, fredrb commented on services/download/src/main/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilter.java
>        app.coronawarn.server.common.protocols.external.exposurenotification.DiagnosisKey federationKey) {
```suggestion
      DiagnosisKey federationKey) {
```
No longer needed as the `exposurenotification.DiagnosisKey` is the only imported class with `DiagnosisKey` name 🙂

2020-10-06 07:51 UTC, fredrb commented on services/download/src/main/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilter.java
> +        && federationKey.getRollingStartIntervalNumber() % maxRollingPeriod == 0;
I suggest you extract this into another method and remove the comment for clarify. For example:
```java
 && rollingStartIntervalIsMidnight(federationKey);
```