Document EUR package
corona-warn-app/cwa-server pull request #884
Opened 2020-10-13 12:31 UTC by sorin-stefan-iovita-sap

## Description
This PR documents the implementation about the EUR distribution package.

2020-10-13 13:06 UTC, KevponSAP requested changes

2020-10-13 13:06 UTC, KevponSAP commented on docs/DISTRIBUTION.md
> +
```suggestion
The `origin_country` (ISO-3166 country code) parameter defines which country folder is being created. The origin country folder contains only the distributable keys for the origin country. Furthermore, based on the parameter`eu-package-name` an additional folder will be created which provides all keys from the supported countries in a single package. 
```

2020-10-14 12:19 UTC, EugenM-SAP commented on docs/DISTRIBUTION.md
> +The `origin_country` (ISO-3166 country code) parameter defines which country folder is being created.
Suggested rewording:
"...parameter refers to the country in which the CWA clients and backend operate. It is used to create a folder on the CDN distribution paths, where so called "national key packages" are distributed. In essence, these packages  contain keys submitted by CWA clients as well as keys from visitors of the country, that have been downloaded from the Federation Gateway Service."

2020-10-15 06:02 UTC, fredrb commented
Maybe we should include that on the origin country we apply all the key sharing policies? While on the EUR keys are distributed immediately?

2020-10-20 11:18 UTC, KevponSAP approved these changes

2020-10-21 06:54 UTC, fredrb approved these changes

2020-10-21 07:26 UTC, merged