Update api documentation including european package
corona-warn-app/cwa-server pull request #885
Opened 2020-10-14 12:03 UTC by KevponSAP

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

Adjusted api documentation to include european package changes

2020-10-14 12:22 UTC, EugenM-SAP commented on services/distribution/api_v1.json
> -    "info": {
Was this file reformated? It's hard to tell the diff

2020-10-14 12:52 UTC, EugenM-SAP approved these changes

2020-10-19 10:11 UTC, EvgeniiSkrebtcov requested changes

2020-10-19 10:11 UTC, EvgeniiSkrebtcov commented on services/distribution/api_v1.json
> +                "description": "Gives application configuration for a specific country, which includes:\n- Minimum risk score\n- Risk score classification\n- Risk score parameters\n- Attenuation dura
We should probably explain this in more detail. E.g. that the app_config is generated for the origin country, and update the values in the file (supported countries).

2020-10-19 10:11 UTC, EvgeniiSkrebtcov commented on services/distribution/api_v1.json
> +                "summary": "Get the country and the common package for which diagnosis keys are available.",
I suggest to explain in more detail what do we mean by "common" package.

2020-10-21 06:55 UTC, fredrb approved these changes

2020-10-21 07:59 UTC, EvgeniiSkrebtcov approved these changes

2020-10-21 08:01 UTC, merged