Set consentToFederation parameter to true in testdata generator
corona-warn-app/cwa-server pull request #886
Opened 2020-10-14 12:18 UTC by KevponSAP

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

Setting the consentToFederation parameter to true while generating diagnosis keys via the distribution testdata generator

2020-10-14 12:36 UTC, sorin-stefan-iovita-sap approved these changes

2020-10-14 12:57 UTC, EugenM-SAP approved these changes
If the intent is to share the keys generated here with EFGS during testing, it's fine.

2020-10-15 05:58 UTC, fredrb requested changes
I'm fine with the code. I would just suggest to change the environment variable name to something more specific. For example `TESTDATA_CONSENT_TO_FEDERATION` or even `DISTRIBUTION_TESTDATA_CONSENT_TO_FEDERATION`. To make it clear that this is used only for test data.

2020-10-15 08:00 UTC, fredrb approved these changes

2020-10-15 08:23 UTC, EugenM-SAP approved these changes
Maybe just a remark, that the env could be even more specific.
"SHARE_TESTDATA_WITH_EFGS" true/false
In the end that's what the goal is.

2020-10-15 12:46 UTC, kilbphilippSAP approved these changes

2020-10-16 08:50 UTC, merged