Centralize logging for download/submission/upload/persistence modules
corona-warn-app/cwa-server pull request #899
Opened 2020-10-20 12:13 UTC by roesslerj

## Description

This PR is according to EXPOSUREBACK-165: Refactor the way logging is done.  This offers following benefits

Easy maintenance of messages that gets logged in one central location.
Any future changes related to log messages would require change only in one file 
This file could be used as starting point in discussions with DPP colleagues
This would also come handy if we need to support multiple languages in future.

To achieve this, we centralized all log messages in one enum per module, all of which implement the same interface. By also implementing a wrapper for the slf4j logger, we achieve type-safety:

- app.coronawarn.server.common.Logger is the slf4j wrapper.
- app.coronawarn.server.common.LogMessages is the centralized interface.
- app.coronawarn.server.common.persistence.service.common.PersistenceLogMessages is the enum for the persistence module implementing the LogMessages interface.

2020-10-21 09:12 UTC, mibrasap requested changes
Let's re-discuss the concept of this change. I see the advantages of having a centralized place for the log messages. The way it is done in this PR will also bring more complexity during development.

2020-10-22 07:31 UTC, kilbphilippSAP commented on common/persistence/src/main/java/app/coronawarn/server/common/persistence/service/FederationBatchInfoService.java
> +    logger.info(MARKET_BATCH_WITH_STATUS, federationBatchInfo.getBatchTag(), statusValue);
```suggestion
    logger.info(MARKED_BATCH_WITH_STATUS, federationBatchInfo.getBatchTag(), statusValue);
```

2020-10-22 07:35 UTC, kilbphilippSAP commented on common/persistence/src/main/java/app/coronawarn/server/common/persistence/service/common/PersistenceLogMessages.java
> +  NR_RETRIEVED_DISCARDED_DIAGNOSIS_KEYS(
NUM / NO to abbreviate number in EN.

2020-10-22 09:28 UTC, roesslerj commented
As just discussed, we will drop this PR for the following reasons: Although centralizing logging statements makes it easier to gather them for DPP, it makes maintaining and adding them a lot more difficult. Using aspects seems to be counter-intuitive in this instance altogether.
Instead, we will create a mvn plugin to gather all logging statements in one file for DPP.

2020-10-22 09:28 UTC, closed without merging