Decode DSOS from values coming from EFGS
corona-warn-app/cwa-server pull request #901
Opened 2020-10-20 12:44 UTC by EugenM-SAP

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

EFGS embeds additional information within the diagnosis keys 'daysSinceOnsetSymptoms' field which can lead to issues when forwarding this key to CWA clients via distribution because the Exposure Notification framework may not accept these values. Thus we need to "decode" the EN value from the EFGS value. This is taken care of in this PR.

2020-10-21 12:25 UTC, sorin-stefan-iovita-sap commented on common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/validation/DaysSinceSymptomsRangeSpecification.java
> +    return Arrays.asList(values()).stream().filter(spec -> spec.accept(originalDaysSinceSymptoms))
```suggestion
    return Arrays.stream(values()).filter(spec -> spec.accept(originalDaysSinceSymptoms))
        .findFirst();
```

2020-10-21 12:25 UTC, sorin-stefan-iovita-sap commented on common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/validation/DaysSinceSymptomsRangeSpecification.java
> +        .findFirst();
```suggestion
    return Arrays.stream(values()).filter(spec -> spec.accept(originalDaysSinceSymptoms))
        .findFirst();
```

2020-10-21 12:31 UTC, sorin-stefan-iovita-sap commented on services/download/src/main/java/app/coronawarn/server/services/download/normalization/DecodedDsosNotInExposureNotificationFrameworkRange.java
> +public class DecodedDsosNotInExposureNotificationFrameworkRange extends RuntimeException {
Suggested naming:
"InvalidDsosException" or something shorter than the current name which ends with '*Exception'.

2020-10-23 07:51 UTC, sorin-stefan-iovita-sap approved these changes

2020-10-23 08:25 UTC, EvgeniiSkrebtcov requested changes
We should consider to undo the DSOS defaulting we implemented to avoid issues with the values out of ENF allowed range.

2020-10-23 08:25 UTC, EvgeniiSkrebtcov commented on services/download/src/main/java/app/coronawarn/server/services/download/normalization/EfgsDaysSinceSymptomsDecoder.java
> + * <p>This class encapsulates the logic to extract the given DSOS value value corresponding to "number
Please correct the comment: "...given DSOS value value corresponding..."

2020-10-23 08:25 UTC, EvgeniiSkrebtcov commented on services/download/src/main/java/app/coronawarn/server/services/download/normalization/EfgsDaysSinceSymptomsDecoder.java
> +                + originalDaysSinceSymptoms + " cannot be decoded"));
KIndly check: EXPOSUREBACK-436 to avoid similar issues.

2020-10-23 08:25 UTC, EvgeniiSkrebtcov commented on common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/validation/DaysSinceSymptomsRangeSpecification.java
> +  ExposureNotificationAcceptedRange(-14, 21, (dsos) -> 0),
Please recheck this with Max. My understanding was that the range should be -14 ->14

2020-10-23 10:52 UTC, EugenM-SAP commented
Cancelling the PR for now, since there are new changes planned for the DSOS / TRL calculations with ithe ntroduction of Exposure Notification Framework v2. Until that time, dsos stays at value '0' for published keys.

2020-10-23 10:52 UTC, closed without merging