Put country information in submission validation logs
corona-warn-app/cwa-server pull request #945
Opened 2020-10-29 08:58 UTC by EugenM-SAP

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

2020-10-29 09:12 UTC, ioangut submitted a review, later dismissed

2020-10-29 11:27 UTC, hilmarf requested changes

2020-10-29 11:27 UTC, hilmarf commented on services/submission/src/test/java/app/coronawarn/server/services/submission/validation/ValidSubmissionPayloadTest.java
> +}
@EugenM-SAP can you please add one more test or assert statement maybe, which test the validation error message?
something like:
`assert error message contains "[ java.lang.Runtime.getRuntime().exec.... ]: Visited country is not part of the supported" countries list"`

2020-11-01 14:07 UTC, sorin-stefan-iovita-sap approved these changes

2020-11-01 16:43 UTC, merged