Feature/download authentication exception
corona-warn-app/cwa-server pull request #955
Opened 2020-11-02 09:54 UTC by FelixRottler

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

- shutdown of the download runner in case of a 403 response from the efgs

2020-11-02 18:51 UTC, hilmarf requested changes

2020-11-02 18:51 UTC, hilmarf commented on services/download/src/main/java/app/coronawarn/server/services/download/BatchDownloadException.java
> +
please remove empty lines at the beginning of the file - the package declaration should be the first statement

2020-11-04 07:49 UTC, roesslerj approved these changes

2020-11-04 07:54 UTC, hilmarf approved these changes

2020-11-04 07:54 UTC, merged